import os

from .star_random_image_loader import NODE_CLASS_MAPPINGS as STAR_RANDOM_IMAGE_LOADER_NODE_CLASS_MAPPINGS
from .star_random_image_loader import NODE_DISPLAY_NAME_MAPPINGS as STAR_RANDOM_IMAGE_LOADER_NODE_DISPLAY_NAME_MAPPINGS
from .star_save_panorama_jpeg import NODE_CLASS_MAPPINGS as STAR_SAVE_PANORAMA_JPEG_NODE_CLASS_MAPPINGS
from .star_save_panorama_jpeg import NODE_DISPLAY_NAME_MAPPINGS as STAR_SAVE_PANORAMA_JPEG_NODE_DISPLAY_NAME_MAPPINGS
from .star_frame_from_video import NODE_CLASS_MAPPINGS as STAR_FRAME_FROM_VIDEO_NODE_CLASS_MAPPINGS
from .star_frame_from_video import NODE_DISPLAY_NAME_MAPPINGS as STAR_FRAME_FROM_VIDEO_NODE_DISPLAY_NAME_MAPPINGS
from .star_image_loader_1by1 import NODE_CLASS_MAPPINGS as STAR_IMAGE_LOADER_1BY1_NODE_CLASS_MAPPINGS
from .star_image_loader_1by1 import NODE_DISPLAY_NAME_MAPPINGS as STAR_IMAGE_LOADER_1BY1_NODE_DISPLAY_NAME_MAPPINGS

NODE_CLASS_MAPPINGS = {
    **STAR_RANDOM_IMAGE_LOADER_NODE_CLASS_MAPPINGS,
    **STAR_SAVE_PANORAMA_JPEG_NODE_CLASS_MAPPINGS,
    **STAR_FRAME_FROM_VIDEO_NODE_CLASS_MAPPINGS,
    **STAR_IMAGE_LOADER_1BY1_NODE_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **STAR_RANDOM_IMAGE_LOADER_NODE_DISPLAY_NAME_MAPPINGS,
    **STAR_SAVE_PANORAMA_JPEG_NODE_DISPLAY_NAME_MAPPINGS,
    **STAR_FRAME_FROM_VIDEO_NODE_DISPLAY_NAME_MAPPINGS,
    **STAR_IMAGE_LOADER_1BY1_NODE_DISPLAY_NAME_MAPPINGS,
}


