import os
from .star_qwen_image_ratio import (
    NODE_CLASS_MAPPINGS as STAR_QWEN_IMAGE_RATIO_NODE_CLASS_MAPPINGS,
)
from .star_qwen_image_ratio import (
    NODE_DISPLAY_NAME_MAPPINGS as STAR_QWEN_IMAGE_RATIO_NODE_DISPLAY_NAME_MAPPINGS,
)
from .star_qwen_wan_ratio import (
    NODE_CLASS_MAPPINGS as STAR_QWEN_WAN_RATIO_NODE_CLASS_MAPPINGS,
)
from .star_qwen_wan_ratio import (
    NODE_DISPLAY_NAME_MAPPINGS as STAR_QWEN_WAN_RATIO_NODE_DISPLAY_NAME_MAPPINGS,
)
from .star_apply_overlay_depth import (
    NODE_CLASS_MAPPINGS as STAR_APPLY_OVERLAY_DEPTH_NODE_CLASS_MAPPINGS,
)
from .star_apply_overlay_depth import (
    NODE_DISPLAY_NAME_MAPPINGS as STAR_APPLY_OVERLAY_DEPTH_NODE_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {
    **STAR_QWEN_IMAGE_RATIO_NODE_CLASS_MAPPINGS,
    **STAR_QWEN_WAN_RATIO_NODE_CLASS_MAPPINGS,
    **STAR_APPLY_OVERLAY_DEPTH_NODE_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **STAR_QWEN_IMAGE_RATIO_NODE_DISPLAY_NAME_MAPPINGS,
    **STAR_QWEN_WAN_RATIO_NODE_DISPLAY_NAME_MAPPINGS,
    **STAR_APPLY_OVERLAY_DEPTH_NODE_DISPLAY_NAME_MAPPINGS,
}

# Expose web assets (including docs) to ComfyUI
# ComfyUI will look for help pages under WEB_DIRECTORY/docs/
WEB_DIRECTORY = "web"



